apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-frontend-deployment
  labels:
    app: express-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-frontend
  template:
    metadata:
      labels:
        app: express-frontend
    spec:
      containers:
      - name: express-frontend
        image: abhisingh7710/flask-node-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL